# mxnet builder
FROM nvidia/cuda:9.1-cudnn7-devel-ubuntu16.04 as mxnet-builder

RUN export DEBIAN_FRONTEND=noninteractive; apt-get update && apt-get -y upgrade \
    && apt install -y python-pip python3-pip graphviz build-essential libopenblas-dev git pkg-config python-opencv libopencv-dev wget unzip libcurl4-openssl-dev liblapack-pic libgoogle-perftools-dev google-perftools libjemalloc-dev revolution-mkl libatlas-base-dev libjpeg-turbo8-dev cython cython3 python-dev python3-dev \
    && apt-get autoremove && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /work

COPY operators /work/operators
COPY mxnet /work/mxnet

RUN cd mxnet \
    && make -j NVCC=/usr/local/cuda/bin/nvcc USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda-9.1/targets/x86_64-linux/ USE_CUDNN=1 USE_NCCL=1 EXTRA_OPERATORS=../operators USE_BLAS=openblas USE_LAPACK_PATH=/usr/lib/x86_64-linux-gnu/openblas/ USE_LIBJPEG_TURBO=0

RUN cd mxnet/python \
    && python2 setup.py sdist && mv dist/mxnet-1.2.0.tar.gz ../mxnet-1.2.0.py2.tar.gz \
    && python2 setup.py bdist_wheel && mv dist/mxnet-1.2.0-py2-none-any.whl ../mxnet-1.2.0-py2-none-any.whl \
    && python3 setup.py sdist && mv dist/mxnet-1.2.0.tar.gz ../mxnet-1.2.0.py3.tar.gz \
    && python3 setup.py bdist_wheel && mv dist/mxnet-1.2.0-py3-none-any.whl ../mxnet-1.2.0-py3-none-any.whl

# deep3d builder
FROM nvidia/cuda:9.1-cudnn7-devel-ubuntu16.04

RUN export DEBIAN_FRONTEND=noninteractive; apt-get update && apt-get -y upgrade \
    && apt install -y python-pip graphviz libopenblas-dev git pkg-config python-opencv libopencv-dev wget unzip libjpeg-turbo8 libjemalloc1 \
    && apt-get autoremove && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /work

COPY --from=mxnet-builder /work/mxnet/mxnet-1.2.0-py2-none-any.whl /work
RUN pip install /work/mxnet-1.2.0-py2-none-any.whl && ln -s /usr/local/mxnet/libmxnet.so /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so

COPY requirements.txt /work
RUN pip install -r requirements.txt

COPY . /work
